export const qwerty =[
    [
        ['`', '~','Backquote'],
        ['1', '!','Digit1'],
        ['2', '@','Digit2'],
        ['3', '#','Digit3'],
        ['4', '$','Digit4'],
        ['5', '%','Digit5'],
        ['6', '^','Digit6'],
        ['7', '&','Digit7'],
        ['8', '*','Digit8'],
        ['9', '(','Digit9'],
        ['0', ')','Digit0'],
        ['-', '_','Minus'],
        ['=', '+','Equal']
    ],[
        ['q', 'Q','KeyQ'],
        ['w', 'W','KeyW'],
        ['e', 'E','KeyE'],
        ['r', 'R','KeyR'],
        ['t', 'T','KeyT'],
        ['y', 'Y','KeyY'],
        ['u', 'U','KeyU'],
        ['i', 'I','KeyI'],
        ['o', 'O','KeyO'],
        ['p', 'P','KeyP'],
        ['[', '{','BracketLeft'],
        [']', '}','BracketRight'],
    ],
    [
        ['a', 'A','KeyA'],
        ['s', 'S','KeyS'],
        ['d', 'D','KeyD'],
        ['f', 'F','KeyF'],
        ['g', 'G','KeyG'],
        ['h', 'H','KeyH'],
        ['j', 'J','KeyJ'],
        ['k', 'K','KeyK'],
        ['l', ':','KeyL'],
        [';', '"',"Semicolon"],
        ['\'', '|','Quote'],

    ],
    [
        ['z', 'Z','KeyZ'],
        ['x', 'X','KeyX'],
        ['c', 'C','KeyC'],
        ['v', 'V','KeyV'],
        ['b', 'B','KeyB'],
        ['n', 'N','KeyN'],
        ['m', 'M','KeyM'],
        [',', '<','Comma'],
        ['.', '>','Period'],
        ['/', '?','Slash'],

    ]
]
export const IslLatin =[
    [
        ['`', '~','Backquote'],
        ['1', '!','Digit1'],
        ['2', '@','Digit2'],
        ['3', '#','Digit3'],
        ['4', '$','Digit4'],
        ['5', '%','Digit5'],
        ['6', '^','Digit6'],
        ['7', ':','Digit7'],
        ['8', '*','Digit8'],
        ['9', '(','Digit9'],
        ['0', ')','Digit0'],
        ['-', '_','Minus'],
        ['=', '+','Equal']
    ],[
        ['ž', 'Ž','KeyQ'],
        ['ě', 'Ě','KeyW'],
        ['e', 'E','KeyE'],
        ['r', 'R','KeyR'],
        ['t', 'T','KeyT'],
        ['y', 'Y','KeyY'],
        ['u', 'U','KeyU'],
        ['i', 'I','KeyI'],
        ['o', 'O','KeyO'],
        ['p', 'P','KeyP'],
        ['[', '{','BracketLeft'],
        [']', '}','BracketRight'],
    ],
    [
        ['a', 'A','KeyA'],
        ['s', 'S','KeyS'],
        ['d', 'D','KeyD'],
        ['f', 'F','KeyF'],
        ['g', 'G','KeyG'],
        ['h', 'H','KeyH'],
        ['j', 'J','KeyJ'],
        ['k', 'K','KeyK'],
        ['l', ':','KeyL'],
        [';', '"',"Semicolon"],
        ['\'', '|','Quote'],

    ],
    [
        ['z', 'Z','KeyZ'],
        ['č', 'Č','KeyX'],
        ['c', 'C','KeyC'],
        ['v', 'V','KeyV'],
        ['b', 'B','KeyB'],
        ['n', 'N','KeyN'],
        ['m', 'M','KeyM'],
        [',', '<','Comma'],
        ['.', '>','Period'],
        ['/', '?','Slash'],

    ]
]

export const IslCyrillic =[
    [
        ['`', '~','Backquote'],
        ['1', '!','Digit1'],
        ['2', '"','Digit2'],
        ['3', '#','Digit3'],
        ['4', ';','Digit4'],
        ['5', '%','Digit5'],
        ['6', ':','Digit6'],
        ['7', '№','Digit7'],
        ['8', '*','Digit8'],
        ['9', '(','Digit9'],
        ['0', ')','Digit0'],
        ['-', '_','Minus'],
        ['=', '+','Equal']
    ],[
        ['j', 'J','KeyQ'],
        ['ц', 'Ц','KeyW'],
        ['у', 'У','KeyE'],
        ['к', 'К','KeyR'],
        ['е', 'Е','KeyT'],
        ['н', 'Н','KeyY'],
        ['г', 'Г','KeyU'],
        ['ш', 'Ш','KeyI'],
        ['њ', 'Њ','KeyO'],
        ['х', 'Х','KeyP'],
        [ '[', '{','BracketLeft'],
        [ ']', '}','BracketRight'],
    ],
    [
        ['ф', 'Ф','KeyA'],
        ['ы', 'Ы','KeyS'],
        ['в', 'В','KeyD'],
        ['а', 'А','KeyF'],
        ['п', 'П','KeyG'],
        ['р', 'Р','KeyH'],
        ['о', 'О','KeyJ'],
        ['л', 'Л','KeyK'],
        ['д', 'Д','KeyL'],
        ['ж', 'Ж',"Semicolon"],
        ['є', 'Є','Quote'],

    ],
    [
        ['з', 'З','KeyZ'],
        ['ч', 'Ч','KeyX'],
        ['с', 'С','KeyC'],
        ['м', 'М','KeyV'],
        ['и', 'И','KeyB'],
        ['т', 'Т','KeyN'],
        ['љ', 'Љ','KeyM'],
        ['б', 'Б','Comma'],
        ['.', ',','Period'],
        ['/', '?','Slash'],

    ]
]
//['њ', 'Њ','KeyM'],
//['љ', 'Љ','BracketRight'],
