export const qwerty =[
    [
        ['`', '~','Backquote',false],
        ['1', '!','Digit1',false],
        ['2', '@','Digit2',false],
        ['3', '#','Digit3',false],
        ['4', '$','Digit4',false],
        ['5', '%','Digit5',false],
        ['6', '^','Digit6',false],
        ['7', '&','Digit7',false],
        ['8', '*','Digit8',false],
        ['9', '(','Digit9',false],
        ['0', ')','Digit0',false],
        ['-', '_','Minus',false],
        ['=', '+','Equal',false],
    ],[
        ['q', 'Q','KeyQ',false],
        ['w', 'W','KeyW',false],
        ['e', 'E','KeyE',false],
        ['r', 'R','KeyR',false],
        ['t', 'T','KeyT',false],
        ['y', 'Y','KeyY',false],
        ['u', 'U','KeyU',false],
        ['i', 'I','KeyI',false],
        ['o', 'O','KeyO',false],
        ['p', 'P','KeyP',false],
        ['[', '{','BracketLeft',false],
        [']', '}','BracketRight',false],
    ],
    [
        ['a', 'A','KeyA',false],
        ['s', 'S','KeyS',false],
        ['d', 'D','KeyD',false],
        ['f', 'F','KeyF',false],
        ['g', 'G','KeyG',false],
        ['h', 'H','KeyH',false],
        ['j', 'J','KeyJ',false],
        ['k', 'K','KeyK',false],
        ['l', ':','KeyL',false],
        [';', '"',"Semicolon",false],
        ['\'', '|','Quote',false],

    ],
    [
        ['z', 'Z','KeyZ',false],
        ['x', 'X','KeyX',false],
        ['c', 'C','KeyC',false],
        ['v', 'V','KeyV',false],
        ['b', 'B','KeyB',false],
        ['n', 'N','KeyN',false],
        ['m', 'M','KeyM',false],
        [',', '<','Comma',false],
        ['.', '>','Period',false],
        ['/', '?','Slash',false],

    ]
]
export const IslLatin =[
    [
        ['`', '~','Backquote',false],
        ['1', '!','Digit1',false],
        ['2', '@','Digit2',false],
        ['3', '#','Digit3',false],
        ['4', '$','Digit4',false],
        ['5', '%','Digit5',false],
        ['6', '^','Digit6',false],
        ['7', ':','Digit7',false],
        ['8', '*','Digit8',false],
        ['9', '(','Digit9',false],
        ['0', ')','Digit0',false],
        ['-', '_','Minus',false],
        ['=', '+','Equal',false],
    ],[
        ['ž', 'Ž','KeyQ',true],
        ['ě', 'Ě','KeyW',true],
        ['e', 'E','KeyE',false],
        ['r', 'R','KeyR',false],
        ['t', 'T','KeyT',false],
        ['y', 'Y','KeyY',false],
        ['u', 'U','KeyU',false],
        ['i', 'I','KeyI',false],
        ['o', 'O','KeyO',false],
        ['p', 'P','KeyP',false],
        ['[', '{','BracketLeft',false],
        [']', '}','BracketRight',false],
    ],
    [
        ['a', 'A','KeyA',false],
        ['s', 'S','KeyS',false],
        ['d', 'D','KeyD',false],
        ['f', 'F','KeyF',false],
        ['g', 'G','KeyG',false],
        ['h', 'H','KeyH',false],
        ['j', 'J','KeyJ',false],
        ['k', 'K','KeyK',false],
        ['l', ':','KeyL',false],
        [';', '"',"Semicolon",false],
        ['\'', '|','Quote',false],

    ],
    [
        ['z', 'Z','KeyZ',false],
        ['č', 'Č','KeyX',true],
        ['c', 'C','KeyC',false],
        ['v', 'V','KeyV',false],
        ['b', 'B','KeyB',false],
        ['n', 'N','KeyN',false],
        ['m', 'M','KeyM',false],
        ['š', 'Š','Comma',true],
        ['.', ',','Period',true],
        ['/', '?','Slash',false],

    ]
]

export const IslCyrillic =[
    [
        ['`', '~','Backquote',false],
        ['1', '!','Digit1',false],
        ['2', '"','Digit2',false],
        ['3', '#','Digit3',true],
        ['4', ';','Digit4',false],
        ['5', '%','Digit5',false],
        ['6', ':','Digit6',false],
        ['7', '№','Digit7',true],
        ['8', '*','Digit8',false],
        ['9', '(','Digit9',false],
        ['0', ')','Digit0',false],
        ['-', '_','Minus',false],
        ['=', '+','Equal',false],
    ],[
        ['j', 'J','KeyQ',true],
        ['ц', 'Ц','KeyW',false],
        ['у', 'У','KeyE',false],
        ['к', 'К','KeyR',false],
        ['е', 'Е','KeyT',false],
        ['н', 'Н','KeyY',false],
        ['г', 'Г','KeyU',false],
        ['ш', 'Ш','KeyI',false],
        ['њ', 'Њ','KeyO',true],
        ['х', 'Х','KeyP',true],
        [ '[', '{','BracketLeft',true],
        [ ']', '}','BracketRight',true],
    ],
    [
        ['ф', 'Ф','KeyA',false],
        ['ы', 'Ы','KeyS',false],
        ['в', 'В','KeyD',false],
        ['а', 'А','KeyF',false],
        ['п', 'П','KeyG',false],
        ['р', 'Р','KeyH',false],
        ['о', 'О','KeyJ',false],
        ['л', 'Л','KeyK',false],
        ['д', 'Д','KeyL',false],
        ['ж', 'Ж',"Semicolon",false],
        ['є', 'Є','Quote',true],

    ],
    [
        ['з', 'З','KeyZ',true],
        ['ч', 'Ч','KeyX',false],
        ['с', 'С','KeyC',false],
        ['м', 'М','KeyV',false],
        ['и', 'И','KeyB',false],
        ['т', 'Т','KeyN',false],
        ['љ', 'Љ','KeyM',true],
        ['б', 'Б','Comma',false],
        ['.', ',','Period',true],
        ['/', '?','Slash',true],

    ]
]
//['њ', 'Њ','KeyM'],
//['љ', 'Љ','BracketRight'],
